
export const femaleProfileImages = [

    "/images/avatar/womanav1.svg",
    "/images/avatar/womanav2.svg",
    "/images/avatar/womanav3.svg",
    "/images/avatar/womanav4.svg",
    "/images/avatar/womanav5.svg",
    "/images/avatar/womanav6.svg",
    "/images/avatar/womanav7.svg",
    "/images/avatar/womanav8.svg",
    "/images/avatar/womanav9.svg",
    "/images/avatar/womanav10.svg",
    "/images/avatar/womanav11.svg",
    "/images/avatar/womanav12.svg",
    "/images/avatar/womanav13.svg",
    "/images/avatar/womanav14.svg",
    "/images/avatar/womanav15.svg",
    "/images/avatar/womanav16.svg",
    "/images/avatar/womanav17.svg",
    "/images/avatar/womanav18.svg",
    "/images/avatar/womanav19.svg",
    "/images/avatar/womanav20.svg",
];

export const maleProfileImages = [
  "/images/avatar/avt1.png",
  "/images/avatar/avt2.png",
  "/images/avatar/avt3.png",
  "/images/avatar/avt4.png",
  "/images/avatar/avt5.png",
  "/images/avatar/avt6.png",
  "/images/avatar/avt7.png",
  "/images/avatar/avt8.png",
  "/images/avatar/avt9.png",
  "/images/avatar/avt10.png",
  "/images/avatar/avt11.png",
  "/images/avatar/avt12.png",
  "/images/avatar/avt13.png",
  "/images/avatar/avt14.png",
  "/images/avatar/avt15.png",
  "/images/avatar/avt16.png",
  "/images/avatar/avt17.png",
  "/images/avatar/avt18.png",
  "/images/avatar/avt19.png",
  "/images/avatar/avt20.png",
  "/images/avatar/avt21.png",
  "/images/avatar/avt22.png",
  "/images/avatar/avt23.png",
  "/images/avatar/avt24.png",
  "/images/avatar/avt25.png",
  "/images/avatar/avt26.png",
  "/images/avatar/avt27.png",
  "/images/avatar/avt28.png",
  "/images/avatar/avt29.png",
  "/images/avatar/avt30.png",
  "/images/avatar/avt31.png",
];
